# Forces new Travis-CI Infrastructure
sudo: false

language: php

env:
  global:
    - RUN_CODECEPTION="no"
    - RUN_UNIT_TESTS="yes"
    - RUN_JAVASCRIPT_TESTS="no"
    - INSTALL_MEMCACHE="yes"
    - INSTALL_MEMCACHED="yes"
    - INSTALL_REDIS="yes"
    - RUN_PHPCS="no"

matrix:
  fast_finish: true
  include:
    - php: 5.3
      env: INSTALL_APC="yes"
    - php: 5.4
      env: INSTALL_APC="yes"
    - php: 5.5
      env: INSTALL_APCU="yes"
    - php: 5.6
      env: INSTALL_APCU="yes"
    - php: 7.0
      env: INSTALL_APCU="yes" RUN_CODECEPTION="yes" RUN_UNIT_TESTS="no" INSTALL_APCU_BC_BETA="no" INSTALL_MEMCACHE="no" INSTALL_MEMCACHED="no" INSTALL_REDIS="no" # Disabled apcu_bc install until https://github.com/travis-ci/travis-ci/issues/5207 is resolved
    - php: 7.1
      env: INSTALL_APCU="yes" RUN_JAVASCRIPT_TESTS="yes" RUN_UNIT_TESTS="no" INSTALL_APCU_BC_BETA="no" INSTALL_MEMCACHE="no" INSTALL_MEMCACHED="no" INSTALL_REDIS="no" # Disabled apcu_bc install until https://github.com/travis-ci/travis-ci/issues/5207 is resolved
    - php: hhvm
      sudo: true
      dist: trusty
      group: edge # until the next update
      addons:
        apt:
          packages:
            - mysql-server-5.6
            - mysql-client-core-5.6
            - mysql-client-5.6
      services:
        - mysql
        - postgresql
        - redis-server
      env: INSTALL_APCU_BC_BETA="no" INSTALL_MEMCACHE="no" INSTALL_MEMCACHED="no" # Disabled items that currently do not work in travis-ci hhvm
  allow_failures:
    - php: hhvm
    - php: 7.0
      env: RUN_PHPCS="yes"
      sudo: true
      dist: trusty

services:
  - memcache
  - memcached
  - redis-server

before_script:
  # Make sure all dev dependencies are installed
  - if [[ $RUN_UNIT_TESTS == "yes" ]]; then bash build/travis/unit-tests.sh $PWD; fi
  # Codeception system tests
  - if [[ $RUN_CODECEPTION == "yes" ]]; then export DISPLAY=:99.0; bash build/travis/codeception-tests.sh $(pwd); fi
  - if [[ $RUN_CODECEPTION == "yes" ]]; then wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb; fi
  - if [[ $RUN_CODECEPTION == "yes" ]]; then sudo dpkg -i google-chrome*.deb; fi
  - if [[ $RUN_CODECEPTION == "yes" ]]; then export CHROME_BIN=/usr/bin/google-chrome; fi

script:
  - if [[ $RUN_UNIT_TESTS == "yes" ]]; then libraries/vendor/bin/phpunit --configuration travisci-phpunit.xml; fi
  - if [[ $RUN_CODECEPTION == "yes" ]]; then tests/codeception/vendor/bin/robo run:tests --use-htaccess; fi
  - if [[ $RUN_CS == "yes" ]]; then tests/codeception/vendor/bin/robo check:codestyle; fi
  - if [[ $RUN_JAVASCRIPT_TESTS == "yes" ]]; then tests/javascript/node_modules/karma/bin/karma start karma.conf.js --single-run ; fi

branches:
  except:
    - 2.5.x
